TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rzbrp100.db
DATA += rzbrp100.proto

#=======================================
include $(TOP)/configure/RULES
